// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5PTcwGBYw3KBodmlfRwYCGqeHGrGzl5g',
    appId: '1:587566095145:web:9f6ad8c452ad76c4a2f538',
    messagingSenderId: '587566095145',
    projectId: 'foodelivery-5ce55',
    authDomain: 'foodelivery-5ce55.firebaseapp.com',
    storageBucket: 'foodelivery-5ce55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hr9UXqcIDfKdXhqxTtictBrKxtu_-zc',
    appId: '1:587566095145:android:569b94938a6bd821a2f538',
    messagingSenderId: '587566095145',
    projectId: 'foodelivery-5ce55',
    storageBucket: 'foodelivery-5ce55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjKDMn5jJjn5g_Up48v20k6JpAr3_MsUE',
    appId: '1:587566095145:ios:37ebc87b0944542ca2f538',
    messagingSenderId: '587566095145',
    projectId: 'foodelivery-5ce55',
    storageBucket: 'foodelivery-5ce55.appspot.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjKDMn5jJjn5g_Up48v20k6JpAr3_MsUE',
    appId: '1:587566095145:ios:37ebc87b0944542ca2f538',
    messagingSenderId: '587566095145',
    projectId: 'foodelivery-5ce55',
    storageBucket: 'foodelivery-5ce55.appspot.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5PTcwGBYw3KBodmlfRwYCGqeHGrGzl5g',
    appId: '1:587566095145:web:234828e4767cad23a2f538',
    messagingSenderId: '587566095145',
    projectId: 'foodelivery-5ce55',
    authDomain: 'foodelivery-5ce55.firebaseapp.com',
    storageBucket: 'foodelivery-5ce55.appspot.com',
  );
}
